### ISSUE TITLE
IoT-SDK-C cross compile prolem

### ISSUE THREAD

**Issue by jinweichen** [Azure/azure-iot-sdk-c#420]
Host platform:   x86  Ubuntu 12.04
target platform:  imx6 arm

- **OS and version used:** <VERSION> 
ubuntu12.04

- **SDK version used:** <VERSION> 
09/19/2017

# Description of the issue:

Hi,
    When I compile the sdk, the following error occur. Could you help to check how to fix this error.Thanks.

Linking C executable iot_c_utility
/work/Digital/JinWeiChen/imx6/usr/curl_install/lib/libcurl.a(libcurl_la-version.o): In function `curl_version':
version.c:(.text+0x5c): undefined reference to `zlibVersion'
/work/Digital/JinWeiChen/imx6/usr/curl_install/lib/libcurl.a(libcurl_la-version.o): In function `curl_version_info':
version.c:(.text+0xdc): undefined reference to `zlibVersion'
/work/Digital/JinWeiChen/imx6/usr/curl_install/lib/libcurl.a(libcurl_la-content_encoding.o): In function `gzip_init_writer':
content_encoding.c:(.text+0x284): undefined reference to `zlibVersion'
content_encoding.c:(.text+0x2a8): undefined reference to `inflateInit2_'
content_encoding.c:(.text+0x2d4): undefined reference to `inflateInit2_'
/work/Digital/JinWeiChen/imx6/usr/curl_install/lib/libcurl.a(libcurl_la-content_encoding.o): In function `exit_zlib':
content_encoding.c:(.text+0x348): undefined reference to `inflateEnd'
/work/Digital/JinWeiChen/imx6/usr/curl_install/lib/libcurl.a(libcurl_la-content_encoding.o): In function `deflate_init_writer':
content_encoding.c:(.text+0x458): undefined reference to `inflateInit_'
/work/Digital/JinWeiChen/imx6/usr/curl_install/lib/libcurl.a(libcurl_la-content_encoding.o): In function `inflate_stream':
content_encoding.c:(.text+0x540): undefined reference to `inflate'
content_encoding.c:(.text+0x660): undefined reference to `inflateEnd'
content_encoding.c:(.text+0x674): undefined reference to `inflateInit2_'
/work/Digital/JinWeiChen/imx6/usr/openssl_install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x10): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x20): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2c): undefined reference to `dlclose'
/work/Digital/JinWeiChen/imx6/usr/openssl_install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x358): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x40c): undefined reference to `dlerror'
/work/Digital/JinWeiChen/imx6/usr/openssl_install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x4b4): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x568): undefined reference to `dlerror'
/work/Digital/JinWeiChen/imx6/usr/openssl_install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x5d8): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x638): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x668): undefined reference to `dlerror'
/work/Digital/JinWeiChen/imx6/usr/openssl_install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x700): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x75c): undefined reference to `dlerror'
/work/Digital/JinWeiChen/imx6/usr/openssl_install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x7b8): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [c-utility/samples/iot_c_utility/iot_c_utility] 错误 1
make[1]: *** [c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 33%] Building C object uamqp/CMakeFiles/uamqp.dir/src/amqp_frame_codec.c.o

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by lakshmisivareddy** [comment]
hi jinweichen ,
use ubuntu14.04 along with fallowing curl & openssl versions
 
curl 7.52.1  libcurl/7.52.1 OpenSSL/1.0.2j

**Comment by jebrando** [comment]
Can you please enter you cmake command line you are using, thank you.

**Comment by jspaith** [comment]
Also @jinweichen the SDK that you're using - 9/19 - is pretty old.  In particular we've fixed a fair number of connectivity problems in the December/January timeline, so I'd recommend you update that as part of this investigation.

**Comment by jinweichen** [comment]
I have updated the SDK to 2018/03/16. 
The toolchain configuration is follow. ./build.sh --toolchain-file  toolchain-imx6.cmake

toolchain-imx6.cmake:
INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Linux)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much

# this is the location of the imx6 toolchain targeting the IS
SET(CMAKE_C_COMPILER  /work/Digital/JinWeiChen/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc)
SET(CMAKE_CXX_COMPILER /work/Digital/JinWeiChen/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++)

# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH /work/Digital/JinWeiChen/sysroots)

#OpenSSL path
set(OPENSSL_ROOT_DIR /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi)
set(OPENSSL_SSL_LIBRARY /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libssl.so)
set(OPENSSL_LIBRARIES /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/)
set(OPENSSL_INCLUDE_DIR /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/openssl)

#libcurl path
set(CURL_INCLUDE_DIR /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include)
set(CURL_LIBRARY /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/lib/libcurl.so)
set(CURL_LIBRARYS /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/lib/)


# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

Compile error:
Linking C executable iothub_client_sample_mqtt_dm
/work/Digital/JinWeiChen/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/../../libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.8.2/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make[2]: *** [iothub_client/samples/iothub_client_sample_mqtt_dm/iothub_client_sample_mqtt_dm] 错误 1
make[1]: *** [iothub_client/samples/iothub_client_sample_mqtt_dm/CMakeFiles/iothub_client_sample_mqtt_dm.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 92%] Built target iothub_ll_client_sample_amqp_shared
make: *** [all] 错误 2

[curl_link_error.zip](https://github.com/Azure/azure-iot-sdk-c/files/1828521/curl_link_error.zip)

**Comment by jinweichen** [comment]
I have set the curl directory as "set(CURL_LIBRARY /work/Digital/JinWeiChen/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/lib/libcurl.so)" in the toolchain file.  and make sure the file is exist in the directory. Why still can't find the curl library. Thank you!

**Comment by ewertons** [comment]
Hi @jinweichen ,
similar issues on the internet forums suggest your toolchain definition is either missing a library requirement or your libraries are not located where they are supposed to.
For example, https://ubuntuforums.org/showthread.php?t=1874047

Maybe if you enable verbose logging to show the link command that can help you debug the issue.
That can be done adding [CMAKE_VERBOSE_MAKEFILE](https://cmake.org/cmake/help/v3.0/variable/CMAKE_VERBOSE_MAKEFILE.html) to your cmake command above, as in:
```
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON <rest of the arguments you used>
```

**Comment by ewertons** [comment]
Hi @jinweichen ,
we will close this issue, but feel free to reopen it if you would like follow up on your question.

Thanks,
Azure IoT Team

**Comment by yzhong94** [comment]
@jinweichen , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
